# Generated by Django 4.2.20 on 2025-12-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='Unknown City', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_email',
            field=models.EmailField(default='noemail@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='main_image',
            field=models.ImageField(default='default_property.jpg', upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Flat', 'Flat'), ('Land', 'Land')], default='House', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(default='No address provided.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Sold', 'Sold')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(default='Untitled Property', max_length=200),
        ),
    ]
