# Generated by Django 4.2.20 on 2025-12-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_property_created_at_property_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='main_image',
            new_name='image',
        ),
    ]
